apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
  namespace: ecomm
  annotations:
    argocd.argoproj.io/tracking-id: ecomm:/Service:ecomm/ecomm-service
# or "elb" for a classic load balancer
spec:
  type: ClusterIP
  selector:
    app: ecomm
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000