apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
  namespace: petapp
spec:
  type: ClusterIP
  selector:
    app: ecomm
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000